### PR TITLE
Extract Observations through extraction service

### PR DESCRIPTION
**Pull request by jafeltra**
I worked on this task with @mgramigna.

# Summary
Implement a search method that is used in the Observation service to extract only Observation resources using the extraction framework.

## New behavior
When using the Observation service endpoint, you now receive back the Observations resources that are extracted using the `CSVObservationExtractor`.

## Code changes
- Implements the search method on the base extraction service class. This method now runs extraction and then translates the results from extraction from a `collection` bundle to a `searchset` bundle that only contains the resources of the current `resourceType`.
- Adds a simple configuration object to the observation service that sets up extraction for only observations
  - Note: The config uses the `url` field to point to CSV files for the two extractors to avoid needing to have CSV files somewhere accessible to the server. However, we don't yet support any other way to provide patient MRNs. We might want to consider ways around this, but for now, the file is committed here.
- Adds a utility function that takes a list of entries and creates a search set bundle with the correct `total`. It also supports filtering entries by their resource type, which is used to ensure services only return resources of their own resource type.

# Testing guidance
You can make a GET request to `localhost:3001/4_0_0/Observation` and see the results. On `master`, the search is not implemented and an error should be returned. When making the same request on this branch, you should see a searchset bundle with 3 Observations returned.

### CODE REVIEW

**Comment by mgramigna** [comment]
@jafeltra rebase

**Comment by mgramigna** [comment]
hehehehe

**Comment by jafeltra** [comment]
@mgramigna sorry I wasn't quite as timely as dependabot, but it's rebased!

**Review by dmendelowitz — APPROVED** [review]
This looks great! I was able to extract Observations as described. My only thought (which is probably outside the scope of this task) is that the person making the request won't get the full detailed error message from the extraction framework since log output goes to the server. Not sure if there's a great way to pass along the error info, also not sure if we would even want to pass it along, just thought it was worth bringing up.

**Comment by mgramigna** [comment]
@dmendelowitz this is a great catch. The way asymmetrik works, it'll catch any error `throw`s that happen within the framework, but it will not persist any error message that log as `logger.error`s and then continue.

Worthwhile to make a task to explore persisting these over to the OperationOutcomes that get returned by the shim. Thoughts?

**Pull request merged**
